### PR TITLE
add docker files

### PR DESCRIPTION
**Pull request by albjeremias**
make docker usable for production or dev :)

### CODE REVIEW

**Comment by mister-monster** [comment]
Issue #2 will change the entrypoint, issue #10 will remove dependencies on pafy and youtube-dl, and config.toml is currently the name of the configuration file for the bot itself, there could be conflicts or confusion with the config.toml referenced in docker-compose.

**Comment by albjeremias** [comment]
So when those issues are solved, you can tell me and ill re-update the docker-compose ;) so it won't break. about the config.toml, what is your suggestion then? I known it's missing to update the README.md ;)

**Comment by mister-monster** [comment]
I mulled over it a little bit and decided I do not want to merge docker files. You can create a repo for them and maintain them and I will link to them in the readme if you do.

**Comment by albjeremias** [comment]
every1 hates my PRs.. :(

**Pull request closed without merging**
